name: gigaeats_app
description: "GigaEats - B2B2C Bulk Food Ordering Platform for Malaysia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^15.1.2

  # Network & API
  dio: ^5.3.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Local Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0

  # Supabase (Primary Backend & Auth)
  supabase_flutter: ^2.8.0

  # Push Notifications (Local only - Firebase removed)
  flutter_local_notifications: ^18.0.1

  # UI & Media
  image_picker: ^1.0.0
  cached_network_image: ^3.2.0
  photo_view: ^0.14.0

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.1.0
  permission_handler: ^12.0.0+1
  uuid: ^4.4.0
  equatable: ^2.0.5
  path: ^1.8.3

  # Error Handling & Functional Programming
  dartz: ^0.10.1

  # Dependency Injection
  injectable: ^2.3.2
  get_it: ^7.6.4

  # Secure Storage
  flutter_secure_storage: ^9.0.0

  # Logging
  logger: ^2.0.2+1

  # Icons & Design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7

  # Real-time Communication
  socket_io_client: ^3.1.2

  # Time formatting
  timeago: ^3.6.1

  # Payment & Location
  geolocator: ^14.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.0
  battery_plus: ^6.0.2
  device_info_plus: ^10.1.2

  # Payment Gateways
  flutter_stripe: ^11.1.0
  http: ^1.1.0
  crypto: ^3.0.3

  # File handling
  file_picker: ^8.0.0+1
  path_provider: ^2.1.1
  csv: ^6.0.0
  excel: ^4.0.0
  share_plus: ^10.0.2
  pdf: ^3.11.1

  # Charts & Data Visualization
  fl_chart: ^0.69.0

  # Local Database & Caching
  sqflite: ^2.3.0
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.0
  local_auth: ^2.3.0
  pin_code_fields: ^8.0.1
  timezone: ^0.10.1
  image: ^4.3.0
  rxdart: ^0.28.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.0
  build_runner: ^2.4.0
  freezed: ^2.4.6

  # Testing & Mocking
  mockito: ^5.4.2

  # Code Generation
  injectable_generator: ^2.4.1
  drift_dev: ^2.14.1
  riverpod_generator: ^2.4.0

  # Code Quality
  # dart_code_metrics: ^5.7.6  # Temporarily disabled due to uuid conflict

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  generate: true

  # TODO: Restore assets section when asset directories are created
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/logos/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
