// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnJhMF-b6liiWAXayDPm-6s9b-9L8eU2E',
    appId: '1:902837007402:web:ebb9a51083e557850bff53',
    messagingSenderId: '902837007402',
    projectId: 'gigaeats-app',
    authDomain: 'gigaeats-app.firebaseapp.com',
    storageBucket: 'gigaeats-app.firebasestorage.app',
    measurementId: 'G-C5T064V38C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAezGZVUVzdb-EMy2Pl8x4r87hUqHp3HBQ',
    appId: '1:902837007402:android:622df3fae28b7eab0bff53',
    messagingSenderId: '902837007402',
    projectId: 'gigaeats-app',
    storageBucket: 'gigaeats-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr6d3AOm6OI1TY25BevaHcpYLM5itca_A',
    appId: '1:902837007402:ios:6b219ce714cb8a370bff53',
    messagingSenderId: '902837007402',
    projectId: 'gigaeats-app',
    storageBucket: 'gigaeats-app.firebasestorage.app',
    iosBundleId: 'com.gigaeats.gigaeatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr6d3AOm6OI1TY25BevaHcpYLM5itca_A',
    appId: '1:902837007402:ios:6b219ce714cb8a370bff53',
    messagingSenderId: '902837007402',
    projectId: 'gigaeats-app',
    storageBucket: 'gigaeats-app.firebasestorage.app',
    iosBundleId: 'com.gigaeats.gigaeatsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnJhMF-b6liiWAXayDPm-6s9b-9L8eU2E',
    appId: '1:902837007402:web:a028f95450a34f600bff53',
    messagingSenderId: '902837007402',
    projectId: 'gigaeats-app',
    authDomain: 'gigaeats-app.firebaseapp.com',
    storageBucket: 'gigaeats-app.firebasestorage.app',
    measurementId: 'G-D8S97PYDDB',
  );

}