// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzUbRkt4BqvVd0qm0sdKqIFaO1-XQVbrg',
    appId: '1:748971412293:web:773a4ac5fc1ee258c2cc2c',
    messagingSenderId: '748971412293',
    projectId: 'gigaeats',
    authDomain: 'gigaeats.firebaseapp.com',
    storageBucket: 'gigaeats.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzUbRkt4BqvVd0qm0sdKqIFaO1-XQVbrg',
    appId: '1:748971412293:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '748971412293',
    projectId: 'gigaeats',
    storageBucket: 'gigaeats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzUbRkt4BqvVd0qm0sdKqIFaO1-XQVbrg',
    appId: '1:748971412293:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '748971412293',
    projectId: 'gigaeats',
    storageBucket: 'gigaeats.firebasestorage.app',
    iosBundleId: 'com.gigaeats.gigaeatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzUbRkt4BqvVd0qm0sdKqIFaO1-XQVbrg',
    appId: '1:748971412293:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '748971412293',
    projectId: 'gigaeats',
    storageBucket: 'gigaeats.firebasestorage.app',
    iosBundleId: 'com.gigaeats.gigaeatsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzUbRkt4BqvVd0qm0sdKqIFaO1-XQVbrg',
    appId: '1:748971412293:web:773a4ac5fc1ee258c2cc2c',
    messagingSenderId: '748971412293',
    projectId: 'gigaeats',
    authDomain: 'gigaeats.firebaseapp.com',
    storageBucket: 'gigaeats.firebasestorage.app',
  );
}
